### PR TITLE
Rt/fix table

### PR DESCRIPTION
**Pull request by rtopfer**
This PR 
1. Replaces the buggy HTML table used for class member attributes with a standard markdown table
2. Folds class attribute details into an HTML drop-down display for much cleaner output rendering

### CODE REVIEW

**Comment by rtopfer** [comment]
@po09i can you try your build using this branch? Hopefully it's much neater!

**Comment by po09i** [comment]
I can't seem to make the current build work with mkdocs. There seems to be an issue with the html detail block. The block is there but when pressed, it renders as plain text instead of the markdown format. How did you make it work?

Alternatively, I did find a way to make it work using [pymdownx.details](https://facelessuser.github.io/pymdown-extensions/extensions/details/#overview). This requires to install it and add pymdownx.detail in the list of extension in the markdown config file. Afterwards the markdown looks like this :
```
??? details

    | Attribute            | Value |
    |:--------------------:|:-----:|
    | Hidden               | false |
    | Sealed               | false |
    | Abstract             | false |
    | Enumeration          | false |
    | ConstructOnLoad      | false |
    | HandleCompatible     | true  |
    | RestrictsSubclassing | false |

    - InferiorClasses : [N/A] 
    - ContainingPackage : [N/A] 
    - EventList : [N/A] 
    - EnumerationMemberList : [N/A] 
    - Superclasses: matlab.mixin.SetGet
```

*Tabs are important*

**Comment by rtopfer** [comment]
:( but it [renders nicely](https://github.com/shimming-toolbox/helpDocMd/blob/rt/fix-table/docs/Documentor.md#documentor) on github itself!

> How did you make it work?

guess it just works out of the box with whatever default build settings github uses?

**Comment by rtopfer** [comment]
@po09i can you try running the main site build with the code on the updated branch? if it works we can merge. You'll need to add "extra" to the list of [extensions](https://python-markdown.github.io/extensions/) in the .yaml config. (Should probably add "nl2br" to the list as well.)

**Comment by po09i** [comment]
I would add back this line
`<summary> Details </summary>`
after all of these lines
`<details markdown="block">`
to make it nicer, aside from that everything works beautifully

**Review by po09i — CHANGES_REQUESTED** [review]
^

**Comment by rtopfer** [comment]
> Alternatively, I did find a way to make it work using [pymdownx.details](https://facelessuser.github.io/pymdown-extensions/extensions/details/#overview). This requires to install it and add pymdownx.detail in the list of extension in the markdown config file. 

For future reference, in case we run into browser issues, a workaround using pymdonwnx is outlined [here](https://facelessuser.github.io/pymdown-extensions/extensions/details/)

**Pull request merged**
